.TH ANALYSE_NGS 1 "02 August 2024"
.SH NAME
analyse_ngs \- processes paired fastq files & booking sheet of NGS reads from editing experiments, for chaelab


.SH SYNOPSIS
.B analyse_ngs
\fB\-\fB\-fastq_dir \fI DIR
\fB\-\fB\-output_dir \fI DIR
\fB\-\fB\-amplicon_book \fI XLSX
\fB\-\fB\-sheet \fI SHEETNAME
\fB\-\fB\-amplicon_fasta_dir \fI DIR
[\fIOPTION\fP]\&.\|.\|.\&

.SH DESCRIPTION
.B analyse_ngs
processes NGS reads from paired fastq files & booking sheet, for chaelab. Use \-\-skip\-to and \-\-stop\-at to run subset of steps.
.SS Steps:
.TP
.B derep:
truncate and dereplicate FASTQ reads using dada2
.TP
.B blast:
BLASTN of truncated, dereplicated reads to reference genome
.TP
.B intersect:
bedtools intersect of BLASTN hits with reference annotations
.TP
.B id-seq:
assign gene identity to truncated, replicated FASTQ reads based on BLASTN hits and intersected genes
.TP
.B id-read:
assign gene identity to reads, and summarise abundance
.TP
.B demultiplex:
demultiplex FASTQ reads by gene
.TP
.B crispresso:
execute Crispresso2 on demultiplexed FASTQ reads
.SS Exit status:
.TP
.B 0
if OK,
.TP
.B 1
if arguments are invalid.


.SH OPTIONS

.SS Generic Programme Information
.TP
.B \-h "," \-\-help
Print this manual and exit.
.TP
.B \-\-readme
Print the README file and exit.

.SS Execution Controls
.TP
.B \-\-skip\-to "," \-\-start\-at \fI string
Specifies step to skip to. Valid values: derep, blast, intersect, id-seq, id-read, demultiplex, crispresso
.TP
.B \-\-stop\-at \fI string
Specifies step to stop at. Valid values: derep, blast, intersect, id-seq, id-read, demultiplex, crispresso

.SS General Parameters
.TP
.B \-d "," \-\-dir "," \-\-output_dir \fI path
Specifies directory to write output files into.
Temporary files will also be generated in this directory.
.TP
.B \-p "," \-\-prefix \fI string
Prefix to prepend to directories and files generated by minorg.
If not provided and \-\-sheet is used, prefix will be sheet name.
Default is analyseNGS.
.TP
.B \-\-sample\-id\-format \fI integer
Format of sample ID. Informs programme how to convert fastq ID to sample ID (e.g. S01 to S01_S1).
See analyse_ngs/scripts/fastq2sample.sh or analyse_ngs/scripts/fastq2sample.R.
Default is 1.
.TP
.B \-\-fastq\-suffix \fI string
Format of fastq file suffix, where '\\d' stands in for 1/2 for paired reads files.
Default is '_L001_R\\d_001'.

.SS Input
.TP
.B \-f "," \-\-fastq "," \-\-fastq_dir \fI path
Path to directory containing FASTQ files
.TP
.B \-\-gz/\-\-unzipped
If \-\-unzipped, input FASTQ files are assumed to be unzipped (i.e. extension .fastq).
Else, assume gzipped (i.e. extension .fastq.gz).
.TP
.B \-e "," \-\-excel "," \-b "," \-\-booking\-sheet "," \-\-amplicon_book \fI path
Path to Excel file of NGS metadata. Use with \-\-sheetname.
.TP
.B \-n "," \-s "," \-\-sheetname "," \-\-sheet \fI string
Name of Excel sheet. Use with \-\-booking\-sheet.
Will be used as prefix if \-\-prefix not used.
.TP
.B \-\-metadata "," \-\-excel\-tsv \fI path
Path to TSV of Excel sheet, generated by analyse_ngs. Use if Excel file not available or to reproduce results.
.TP
.B \-\-excel\-gene\-pattern \fI string
Gene regex, used with str_extract in R to get gene ID from PCR_Product_fa field of Excel file.
Default is '([^_]+)$'.

.SS Dereplication Options
.TP
.B \-t "," \-\-truncation \fI integer
Number of bp to trim reads to from 5' end (default=70).
Try to set this value so that editing site is not included.
.TP
.B \-\-maxEE \fI numeric
maxEE parameter for dada2::filterAndTrim (default=2)
.TP
.B \-\-rm\-phix \fI boolean
rm.phix parameter for dada2::filterAndTrim (default=TRUE)
.TP
.B \-m "," \-\-multithread \fI boolean
multithread parameter for dada2::filterAndTrim (default=TRUE)

.SS Reference Genome Options
.TP
.B \-\-assembly \fI path
Path to reference assembly FASTA file to BLAST trimmed read sequences against.
Default is TAIR10 (path varies depending on machine).
.TP
.B \-\-gff \fI path
Path to reference annotation GFF file to intersect with BLAST hits.
Default is TAIR10 (path varies depending on machine).

.SS BLAST Options
.TP
.B \-\-blast\-short\-threshold \fI integer
Maximum length for blastn-short task; trimmed reads longer that this will use blastn task (default=50)

.SS CRISPRESSO2 Wrapper Options
.TP
.B \-\-crispresso\-wrapper\-version \fI integer
Crispresso2_wrapper version (default=4)
.TP
.B \-\-editor \fI string
Editor, used to inform cleavage site and editing window. Valid values: Cas9, ABE, unknown (default=Cas9)
.PP
.nf
.RS
Cas9: <default CRISPResso2>
ABE: \-\-cleavage_offset \-12 \-\-quantification_window_size 6
unknown: <sets assessment window to span gRNA (+1 bp 3' if gRNA length is odd)>
.RE
.fi
.TP
.B \-\-amplicon_fasta_dir \fI path
Directory of amplicon FASTA files
